networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: psyblog
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3301:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./backend/backups:/backups
    networks:
      - dev

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: psyblog
    volumes:
      - ./backend:/usr/backend
    networks:
      - dev

  frontend:
    build: .
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - dev

volumes:
  db-data:
